# Set update schedule for GitHub Actions
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#example-dependabotyml-file-for-github-actions

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
      time: '22:00'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      # Check for updates to npm every week
      interval: 'weekly'
      time: '22:00'
